OPP: Handle Stale Data Exception
Use case:
1. Share numerous files
2. Wait for complete
3. View completed transfers
4. Before open transfer history
   click on home button
5. Repeat above steps numerous times

Failure:
Crash in com.android.bluetooth
Msg: StaleDataException, Attempting to access a
     closed Cursor Window

FATAL EXCEPTION: main
Process: com.android.bluetooth, PID: 14080
android.database.StaleDataException: Attempting to access a closed
CursorWindow.Most probable cause: cursor is deactivated prior to
calling this method.
at android.database.AbstractWindowedCursor.checkPosition
   (AbstractWindowedCursor.java:139)
at android.database.AbstractWindowedCursor.getInt
   (AbstractWindowedCursor.java:68)
at android.database.CursorWrapper.getInt(CursorWrapper.java:122)
at com.android.bluetooth.opp.BluetoothOppTransferHistory.getCleara
   bleCount(BluetoothOppTransferHistory.java:296)
at com.android.bluetooth.opp.BluetoothOppTransferHistory.onPrepare
   OptionsMenu(BluetoothOppTransferHistory.java:206)
at android.app.Activity.onPreparePanel(Activity.java:3026)
at com.android.internal.policy.PhoneWindow.preparePanel
   (PhoneWindow.java:599)

Root cause:
Some rare cases after pausing activity also cursor
is trying to fetch values from OPP DB.

Fix:
Catch Cursor Exception to avoid crash in opp profile
and break loop If we get at least one finished transfer
from DB to avoid UN necessary iterations.

CRs-Fixed: 1105353
Change-Id: I9c76638c162e9433b0aa17b99711557ba8f9ef07